import{S as L,a as E,i as m}from"./assets/vendor-ed396e71.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const w=document.querySelector(".gallery-images"),v=new L(".gallery-images a",{captionDelay:250});function p(l){const s=l.map(({webformatURL:a,largeImageURL:i,tags:e,likes:t,views:n,comments:f,downloads:h})=>`<li class = "list-item">
      <a href="${i}" ><img class="search-image" src = "${a}" alt = "${e}" ><div class="options">
      <p class="options-item"> likes:<span class="options-item-span">${t}</span></p>
      <p class="options-item"> views:<span class="options-item-span">${n}</span></p>
      <p class="options-item"> comments:<span class="options-item-span">${f}</span></p>
      <p class="options-item"> downloads:<span class="options-item-span">${h}</span></p></div>
    
      </a>
      
      </li>`).join("");w.insertAdjacentHTML("beforeend",s),v.refresh()}async function u(l,s=1){const a="https://pixabay.com",i="41909271-8b5dab2225a1cd5a9757159a5",e="api/";try{return(await E.get(`${a}/${e}`,{params:{key:i,q:l,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:40,page:s}})).data}catch(t){iziToast.error({title:"Error",titleSize:"30",messageSize:"25",message:"Sorry! Try later! Server not working"}),console.error(t.message)}}const o={formEl:document.querySelector(".form-search"),galleryEL:document.querySelector(".gallery-images"),loadMoreEl:document.querySelector('[data-action="load-more"]'),preloader:document.getElementById("preloader"),loaderGallery:document.querySelector(".loader-gallery")},r="is-hidden";let c="",d=1,y=0;o.formEl.addEventListener("submit",M);async function M(l){l.preventDefault(),o.galleryEL.innerHTML="",o.loadMoreEl.classList.add(r),o.loaderGallery.classList.remove(r),d=1;const s=l.currentTarget;if(c=s.elements.query.value.trim(),!c){o.loaderGallery.classList.add(r),o.loadMoreEl.classList.add(r),m.show({title:"❌",messageColor:"white",message:"Sorry, You have not entered any word.Please try again!",position:"topRight",color:"yellow"});return}try{const{hits:a,totalHits:i}=await u(c);if(a.length===0){o.loadMoreEl.classList.add(r),m.show({title:"❌",messageColor:"white",message:"Sorry, we dont have any pictures for your request.Please try again!",messageSize:"25",position:"topRight",color:"yellow"});return}y=Math.ceil(i/40),p(a),a.length>0&&a.length!==i?(o.loadMoreEl.classList.remove(r),o.loadMoreEl.addEventListener("click",g)):o.loadMoreEl.classList.add(r)}catch{console.log(err)}finally{o.loaderGallery.classList.add(r),s.reset()}}async function g(){d+=1,o.preloader.classList.remove(r),o.loadMoreEl.classList.add(r),o.loadMoreEl.disabled=!0;const l=document.querySelector(".list-item").getBoundingClientRect();try{const{hits:s}=await u(c,d);p(s)}catch(s){console.log(s)}finally{window.scrollBy({top:l.height*2,left:0,behavior:"smooth"}),o.preloader.classList.add(r),o.loadMoreEl.disabled=!1,o.loadMoreEl.classList.remove(r),d===y&&(o.loadMoreEl.classList.add(r),o.loadMoreEl.removeEventListener("click",g),m.show({title:"Finish",messageColor:"white",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",color:"blue"}))}}
//# sourceMappingURL=commonHelpers.js.map
